#!/usr/bin/env python3
"""Build people.md for the arabic-letter skill from a folder of person notes.

Each note is Markdown with YAML frontmatter. A person is included when the note has
`name_ar`; `title_ar`, `org_ar` and `internal` (true/false) are optional. Standard
library only.

Usage: python3 build_people.py <people_folder> <output people.md>
"""
import os, re, sys

FM = re.compile(r"\A---\r?\n(.*?)\r?\n---", re.S)

def frontmatter(path):
    m = FM.match(open(path, encoding="utf-8").read())
    out = {}
    if m:
        for line in m.group(1).splitlines():
            g = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
            if g:
                out[g.group(1).lower()] = g.group(2).strip().strip("\"'")
    return out

def main(folder, dest):
    rows = []
    for f in sorted(os.listdir(folder)):
        if not f.endswith(".md"):
            continue
        fm = frontmatter(os.path.join(folder, f))
        if not fm.get("name_ar"):
            continue
        internal = fm.get("internal", "").lower() in ("true", "yes")
        rows.append((fm.get("title") or f[:-3], fm["name_ar"], fm.get("title_ar", ""),
                     fm.get("org_ar", ""), "internal" if internal else "external"))
    with open(dest, "w", encoding="utf-8") as out:
        out.write("# People (generated)\n\nGenerated by scripts/build_people.py. Do not edit; edit the source notes and rebuild.\n\n")
        out.write("| Name | Arabic name | Arabic title | Arabic organization | Internal/external |\n|---|---|---|---|---|\n")
        for r in rows:
            out.write("| " + " | ".join(r) + " |\n")
    print(f"{len(rows)} people written to {dest}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
